# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # The pack build command is how Buildpacks are executed
      # Replace with your specific image name and other pack build arguments
      pack build us-east5-docker.pkg.dev/$PROJECT_ID/udemy-cloud-run/my-buildpack-image:latest \
        --builder gcr.io/buildpacks/builder \
        --path .
options:
  logging: CLOUD_LOGGING_ONLY
