# steps:
# - name: 'gcr.io/buildpacks/builder' # This image is designed for Buildpacks and includes 'pack'
#   args:
#     - 'pack'
#     - 'build'
#     - 'us-east5-docker.pkg.dev/gcp-pse-457515/udemy-cloud-run/my-buildpack-image:latest' # Replace with your target image name
#     - '--builder'
#     - 'gcr.io/buildpacks/builder' # Specify the builder again, if needed, or omit if default
#     - '--path'
#     - '.' # Path to your source code
# options:
#   logging: CLOUD_LOGGING_ONLY # Keep your logging option

# steps:
# - name: 'gcr.io/buildpacks/builder'
#   args:
#   - 'pack'
#   - 'build'
#   - 'us-east5-docker.pkg.dev/gcp-pse-457515/udemy-cloud-run/my-buildpack-image:latest'
#   - '--path=.'
#   # Optionally add '--builder gcr.io/buildpacks/builder' if your setup explicitly requires it,
#   # but often it's implied when using the builder image directly for the step.
# options:
#   logging: CLOUD_LOGGING_ONLY

# steps:
# - name: 'gcr.io/k8s-skaffold/pack' # Use the dedicated Cloud Build 'pack' builder
#   entrypoint: 'pack' # Explicitly set 'pack' as the entrypoint for this builder
#   args:
#   - 'build'
#   - 'us-east5-docker.pkg.dev/gcp-pse-457515/udemy-cloud-run/my-buildpack-image:latest'
#   - '--builder=gcr.io/buildpacks/builder:latest' # Specify the actual builder image for 'pack'
#   - '--path=.'
#   - '--trust-builder' # Fixes status code 51
#   - '--publish'       # Direct push to registry, bypasses daemon errors
# options:
#   logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    pack build us-east5-docker.pkg.dev/gcp-pse-457515/udemy-cloud-run/lab-06-get-customers-svc-img:latest \
    --builder=gcr.io/buildpacks/builder:latest \
    --path=lab-6-build-and-deploy-cloud-run-service-using-buildpacks/microservices/customers \
    --trust-builder \
    --publish
#    - '--env=GOOGLE_ENTRYPOINT=python main.py' # Replace 'your_script_name.py' with your actual entrypoint script
options:
  logging: CLOUD_LOGGING_ONLY



