@PROJECT_HASH = 24224655199


###

curl --request GET \
  --url https://lab-06-get-customers-svc-24224655199-us-east5.run.app/getcustomers \
  --header 'content-type: application/json' \
  --header 'user-agent: vscode-restclient'

